### PR TITLE
Add test for multiple port 0

### PR DESCRIPTION
**Pull request by victorb**
Current state:

screen shot 2017-08-28 at 14 02 12

### CODE REVIEW

**Comment by victorb** [comment]
Found something that is stopping two identical addresses from being added: https://github.com/libp2p/js-peer-info/blob/422d0fd37ec5e34d6af00eb0d03630b8add37a72/src/multiaddr-set.js#L16-L18

This check is probably too early as two addresses with port 0 should be allowed

**Comment by daviddias** [comment]
@VictorBjelkholm interesting. That is definitely a bummer. Probably there should be a clause that for the same network interface, there can be multiple `port 0`. Wanna push a patch?

**Comment by victorb** [comment]
@diasdavid yeah, tried just commenting out that part linked in https://github.com/libp2p/js-libp2p-swarm/pull/227#issuecomment-325389200 but was not the only place. Still working on getting something functional together.

**Comment by daviddias** [comment]
@VictorBjelkholm are you still working on this? Should we open it for contribution?

**Comment by victorb** [comment]
@diasdavid yes, we need this for isolating tests so we'll need to soon-ish. Open up for contribution :+1:

**Pull request closed without merging**
