### PR TITLE
fix: Uncaught Error: socket hang up

### PR DESCRIPTION
**Pull request by daviddias**
WIP

### CODE REVIEW

**Comment by daviddias** [comment]
I've just pushed my latest changes (for debugging) onto this branch, to test it quickly, run with `./node_modules/.bin/mocha test/05-muxing-spdy.node.js`

**Comment by daviddias** [comment]
I've also added listeners for the error and close events on the tcp sockets created (inside the libp2p-tcp that gets installed on the node_modules) just to check if the error was leaking. I indeed catch the error on the 'close' event, as expected, but still, it gets thrown as an uncaught exception

**Comment by dignifiedquire** [comment]
lgtm with a better commit message

**Comment by daviddias** [comment]
better commit message added. This is a great bug fix! :D

**Pull request merged**
