### PR TITLE
fix: reduce bundle size

### PR DESCRIPTION
**Pull request by hugomrdias**
gziped js-libp2p-switch	258.29	180	-30.31089086%

### CODE REVIEW

**Comment by jacobheun** [comment]
@hugomrdias several of the reduce bundle size PRs have these browser build failures. Perhaps there's an issue with the aegir branch?

```
> aegir test -t browser
Test Browser
15 12 2018 22:41:53.236:ERROR [preprocess]: Can not load "webpack", it is not registered!
  Perhaps you are missing some plugin?
15 12 2018 22:41:53.239:ERROR [preprocess]: Can not load "sourcemap", it is not registered!
  Perhaps you are missing some plugin?
15 12 2018 22:41:53.241:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:mocha"! (Resolving: framework:mocha)
Command failed: karma start /tmp/jenkins/workspace/p2p_js-libp2p-switch_PR-292-3GLYD7TMXTCMDWFOIIDX2R4GR7SKHO2LGZ435L6DUIA2UKUCU7BQ@2/node_modules/aegir/src/config/karma.conf.js --files-custom --log-level error
Error: Command failed: karma start /tmp/jenkins/workspace/p2p_js-libp2p-switch_PR-292-3GLYD7TMXTCMDWFOIIDX2R4GR7SKHO2LGZ435L6DUIA2UKUCU7BQ@2/node_modules/aegir/src/config/karma.conf.js --files-custom --log-level error
    at makeError (/tmp/jenkins/workspace/p2p_js-libp2p-switch_PR-292-3GLYD7TMXTCMDWFOIIDX2R4GR7SKHO2LGZ435L6DUIA2UKUCU7BQ@2/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/tmp/jenkins/workspace/p2p_js-libp2p-switch_PR-292-3GLYD7TMXTCMDWFOIIDX2R4GR7SKHO2LGZ435L6DUIA2UKUCU7BQ@2/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libp2p-switch@0.41.3 test:browser: `aegir test -t browser`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libp2p-switch@0.41.3 test:browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by hugomrdias** [comment]
I saw that already it's the wierd stuff karma does to load plugins.. I'm investigating, normally a restart tests or clean npm install fixes that. Locally using yarn I don't have that problem but I'll make sure everything is fine once I start bubbling up PRs.

**Comment by hugomrdias** [comment]
@jacobheun this PR is ready to merge/release

**Review by jacobheun — APPROVED** [review]
Also verified against the libp2p test suite.

**Pull request merged**
